// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJku10XucUxhCH9k0NgIqOXEKFZFcOzMg',
    appId: '1:313538072618:web:650574bed98b6f73d03353',
    messagingSenderId: '313538072618',
    projectId: 'reddit-clone-52bf1',
    authDomain: 'reddit-clone-52bf1.firebaseapp.com',
    storageBucket: 'reddit-clone-52bf1.firebasestorage.app',
    measurementId: 'G-2C9Q58F9PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAGRPz-cogIXfL29u44a5OpYU7UCbH5LQ',
    appId: '1:313538072618:android:46b463ef89e5277dd03353',
    messagingSenderId: '313538072618',
    projectId: 'reddit-clone-52bf1',
    storageBucket: 'reddit-clone-52bf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDhXm9o27zlk1BMFEBGRIb77dB6q_hMdU',
    appId: '1:313538072618:ios:59b05b8684cce0d9d03353',
    messagingSenderId: '313538072618',
    projectId: 'reddit-clone-52bf1',
    storageBucket: 'reddit-clone-52bf1.firebasestorage.app',
    iosClientId: '313538072618-g5e8kd6eq6a5uupv4ab5kik85mfk9ndh.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDhXm9o27zlk1BMFEBGRIb77dB6q_hMdU',
    appId: '1:313538072618:ios:59b05b8684cce0d9d03353',
    messagingSenderId: '313538072618',
    projectId: 'reddit-clone-52bf1',
    storageBucket: 'reddit-clone-52bf1.firebasestorage.app',
    iosClientId: '313538072618-g5e8kd6eq6a5uupv4ab5kik85mfk9ndh.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJku10XucUxhCH9k0NgIqOXEKFZFcOzMg',
    appId: '1:313538072618:web:539b945c0240c76dd03353',
    messagingSenderId: '313538072618',
    projectId: 'reddit-clone-52bf1',
    authDomain: 'reddit-clone-52bf1.firebaseapp.com',
    storageBucket: 'reddit-clone-52bf1.firebasestorage.app',
    measurementId: 'G-WBKBHLZR91',
  );

}